/* ─────────────────────────────────────────────────────────────
   MOBILE APP FALLBACK DATASET
   Matches Flutter package_service.dart, destination_service.dart,
   and theme_service.dart exactly to ensure 100% data parity.
───────────────────────────────────────────────────────────── */

export const FALLBACK_PACKAGES = [
  {
    _id: '1',
    id: '1',
    packageCode: 'PKG-GOA-001',
    title: 'Vibrant Goa Beach & Water Sports Getaway',
    slug: 'vibrant-goa-beach-getaway-4-days',
    destination: 'Goa, India',
    duration: '4 Days / 3 Nights',
    startingPrice: 12900,
    price: 12900,
    originalPrice: 15900,
    category: 'Domestic',
    theme: 'Leisure',
    themeName: 'Leisure',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'Experience North and South Goa beach hopping, Mandovi river sunset cruise, and thrill water sports in Calangute.',
    highlights: ['4-Star Beach Resort Stay', 'Mandovi River Sunset Cruise', 'Parasailing & Jet Skiing Combo', 'Old Goa Churches'],
    itinerary: [
      { day: 1, title: 'Arrival & Beach Chill', description: 'Airport transfer, check-in to resort, and evening stroll at Baga beach.' },
      { day: 2, title: 'North Goa & Water Sports', description: 'Parasailing, jet skiing, banana ride, and Fort Aguada photoshoot.' },
      { day: 3, title: 'South Goa & Sunset Cruise', description: 'Visit Basilica of Bom Jesus, Mangueshi Temple, and Mandovi river cruise.' },
      { day: 4, title: 'Departure', description: 'Breakfast & souvenir shopping before airport drop.' },
    ],
    inclusions: ['4-Star Resort Stay', 'Daily Buffet Breakfast', 'Private AC Sedan Airport Transfer', 'Water Sports Combo'],
    exclusions: ['Flight Airfare', 'Personal Expenses'],
    pricingTiers: [
      { category: 'Standard', price: 12900, hotel: '3 Star Beachside Hotel', meal: 'Daily Breakfast', transport: 'Shared AC Coach' },
      { category: 'Deluxe', price: 15900, hotel: '4 Star Luxury Resort', meal: 'Breakfast & Dinner', transport: 'Private AC Sedan' },
      { category: 'Luxury', price: 24900, hotel: '5 Star Taj / Marriott Beach Resort', meal: 'All Meals Included', transport: 'Private SUV' },
    ],
    isFeatured: true,
    rating: 4.88,
  },
  {
    _id: '2',
    id: '2',
    packageCode: 'PKG-HIM-001',
    title: 'Scenic Manali & Solang Snow Adventure',
    slug: 'scenic-manali-solang-snow-adventure-5-days',
    destination: 'Himachal Pradesh, India',
    duration: '5 Days / 4 Nights',
    startingPrice: 16500,
    price: 16500,
    originalPrice: 19500,
    category: 'Domestic',
    theme: 'Hill Station',
    themeName: 'Hill Station',
    coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'Explore Hadimba Temple, Mall Road shopping, Solang Valley ATV rides & Rohtang snow point.',
    highlights: ['Solang Valley Snow Sports', 'Rohtang Pass Day Trip', 'Private Mountain View Resort'],
    itinerary: [
      { day: 1, title: 'Arrival in Manali', description: 'Check-in to mountain resort and rest.' },
      { day: 2, title: 'Local Sightseeing', description: 'Hadimba Temple, Vashisht Hot Springs, and Mall Road.' },
      { day: 3, title: 'Solang Valley Adventure', description: 'Paragliding, ropeway, and snow sports.' },
      { day: 4, title: 'Atal Tunnel & Sissu', description: 'Excursion to Lahaul valley via Atal Tunnel.' },
      { day: 5, title: 'Departure', description: 'Breakfast & Volvo bus drop.' },
    ],
    inclusions: ['Mountain View Resort Stay', 'Breakfast & Dinner', 'Private Cab Sightseeing'],
    exclusions: ['Heater Charges', 'Personal Shopping'],
    pricingTiers: [
      { category: 'Standard', price: 16500, hotel: '3 Star Mountain View Hotel', meal: 'Breakfast & Dinner', transport: 'Private Alto/Dzire' },
      { category: 'Deluxe', price: 21900, hotel: '4 Star Luxury Cottage Resort', meal: 'Breakfast & Dinner', transport: 'Private Etios/Sedan' },
      { category: 'Luxury', price: 32000, hotel: '5 Star Span Resort & Spa', meal: 'All Meals Included', transport: 'Private Innova Crysta' },
    ],
    isFeatured: true,
    rating: 4.92,
  },
  {
    _id: '3',
    id: '3',
    packageCode: 'PKG-MAL-001',
    title: 'Maldives Private Water Villa & Snorkeling Paradise',
    slug: 'maldives-water-villa-honeymoon-5-days',
    destination: 'Maldives',
    duration: '5 Days / 4 Nights',
    startingPrice: 59000,
    price: 59000,
    originalPrice: 68000,
    category: 'International',
    theme: 'Honeymoon Tour',
    themeName: 'Honeymoon Tour',
    coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: '5-star private island resort with glass floor water bungalow, speedboat transfer & all meals.',
    highlights: ['Overwater Bungalow with Ocean Access', 'Speedboat Airport Transfer', 'Sunset Dolphin Cruise'],
    itinerary: [
      { day: 1, title: 'Speedboat Welcome to Resort', description: 'Speedboat transfer to island resort & overwater bungalow check-in.' },
      { day: 2, title: 'Snorkeling & House Reef Exploration', description: 'Guided snorkeling session among coral reefs & sea turtles.' },
      { day: 3, title: 'Sunset Dolphin Cruise', description: 'Romantic boat cruise with champagne & dolphin sightings.' },
      { day: 4, title: 'Island Spa & Leisure', description: 'Relaxing couples massage and beachside dinner.' },
      { day: 5, title: 'Departure', description: 'Buffet breakfast & speedboat transfer to Male International Airport.' },
    ],
    inclusions: ['5-Star Overwater Bungalow Stay', 'All-Inclusive Full Board Meals', 'Roundtrip Speedboat Airport Transfer', 'Guided Snorkeling Equipment'],
    exclusions: ['International Flight Tickets', 'Spa Premium Treatments'],
    pricingTiers: [
      { category: 'Standard', price: 59000, hotel: 'Beach Villa with Lagoon Access', meal: 'Breakfast & Dinner', transport: 'Shared Speedboat' },
      { category: 'Deluxe', price: 79000, hotel: 'Overwater Bungalow with Sunset View', meal: 'Full Board (All Meals)', transport: 'Express Speedboat' },
      { category: 'Luxury', price: 115000, hotel: 'Private Pool Ocean Suite', meal: 'Ultra All-Inclusive Premium Drinks', transport: 'Private Seaplane Flight' },
    ],
    isFeatured: true,
    rating: 4.96,
  },
  {
    _id: '4',
    id: '4',
    packageCode: 'PKG-KER-001',
    title: 'Kerala Backwaters & Munnar Hills Luxury Tour',
    slug: 'kerala-backwaters-munnar-luxury-tour-6-days',
    destination: 'Kerala, India',
    duration: '6 Days / 5 Nights',
    startingPrice: 18900,
    price: 18900,
    originalPrice: 22500,
    category: 'Domestic',
    theme: 'Family Tour',
    themeName: 'Family Tour',
    coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'Explore tea gardens of Munnar, Periyar wildlife sanctuary, and overnight luxury houseboat cruise in Alleppey.',
    highlights: ['Overnight Private Houseboat Cruise', 'Munnar Tea Plantation Tour', 'Periyar Boat Safari'],
    itinerary: [
      { day: 1, title: 'Cochin to Munnar Drive', description: 'Scenic drive past Cheeyappara waterfalls to Munnar tea country.' },
      { day: 2, title: 'Munnar Tea Gardens & Eravikulam', description: 'Visit Tea Museum, Mattupetty Dam, and spot Nilgiri Tahr.' },
      { day: 3, title: 'Thekkady Wildlife Sanctuary', description: 'Drive to Thekkady, spice plantation visit, and evening Kathakali show.' },
      { day: 4, title: 'Alleppey Houseboat Cruise', description: 'Board luxury private houseboat, traditional Kerala lunch & canal cruise.' },
      { day: 5, title: 'Kovalam Beach Resort', description: 'Drive to Kovalam beach for relaxation and seafood.' },
      { day: 6, title: 'Trivandrum Departure', description: 'Visit Padmanabhaswamy temple & drop at Trivandrum Airport.' },
    ],
    inclusions: ['Munnar & Thekkady Resort Stays', 'Private Luxury Houseboat Cruise', 'Daily Breakfast & Houseboat All Meals', 'Private AC Sedan Car'],
    exclusions: ['Train / Flight Ticket', 'Kathakali Entry Tickets'],
    pricingTiers: [
      { category: 'Standard', price: 18900, hotel: '3 Star Resort & Deluxe Houseboat', meal: 'Daily Breakfast', transport: 'Private Sedan' },
      { category: 'Deluxe', price: 24500, hotel: '4 Star Tea Garden Resort & Luxury Houseboat', meal: 'Breakfast & Dinner', transport: 'Private Etios' },
      { category: 'Luxury', price: 38900, hotel: '5 Star Taj Kumarakom / Spice Village', meal: 'All Meals Included', transport: 'Private Innova Crysta' },
    ],
    isFeatured: true,
    rating: 4.91,
  },
  {
    _id: '5',
    id: '5',
    packageCode: 'PKG-TEL-001',
    title: 'Telangana & Hyderabad City of Pearls Heritage Tour',
    slug: 'telagana-hyderabad-heritage-tour-4-days',
    destination: 'TELAGANA',
    duration: '4 Days / 3 Nights',
    startingPrice: 11900,
    price: 11900,
    originalPrice: 14500,
    category: 'Domestic',
    theme: 'Family Tour',
    themeName: 'Family Tour',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop'],
    overview: 'Explore Charminar, Golconda Fort sound & light show, Ramoji Film City day excursion & Hussain Sagar lake.',
    highlights: ['Golconda Fort Light & Sound Show', 'Full Day Ramoji Film City Pass', 'Hussain Sagar Sunset Boat Cruise'],
    itinerary: [
      { day: 1, title: 'Arrival & Old City Walk', description: 'Check-in to 4-star hotel, visit Charminar and Laad Bazaar shopping.' },
      { day: 2, title: 'Golconda & Qutb Shahi Tombs', description: 'Guided tour of Golconda Fort and evening sound & light show.' },
      { day: 3, title: 'Ramoji Film City Excursion', description: 'Full day magical film city tour with live stunt shows and studio sets.' },
      { day: 4, title: 'Hussain Sagar & Departure', description: 'Visit Buddha Statue, Salar Jung Museum and airport transfer.' },
    ],
    inclusions: ['4-Star City Hotel Stay', 'Daily Buffet Breakfast', 'Private AC Vehicle', 'Ramoji Film City Tickets'],
    exclusions: ['Airfare / Train Tickets', 'Personal Shopping'],
    pricingTiers: [
      { category: 'Standard', price: 11900, hotel: '3 Star Business Hotel', meal: 'Breakfast Included', transport: 'Shared AC Coach' },
      { category: 'Deluxe', price: 14900, hotel: '4 Star Luxury Hotel', meal: 'Breakfast & Dinner', transport: 'Private AC Sedan' },
      { category: 'Luxury', price: 24900, hotel: '5 Star Taj Falaknuma / Park Hyatt', meal: 'All Meals Included', transport: 'Private SUV' },
    ],
    isFeatured: true,
    rating: 4.85,
  },
  {
    _id: '6',
    id: '6',
    packageCode: 'PKG-RAJ-001',
    title: 'Royal Rajasthan Forts, Palaces & Desert Safari',
    slug: 'rajasthan-royal-forts-desert-safari-6-days',
    destination: 'Rajasthan',
    duration: '6 Days / 5 Nights',
    startingPrice: 19900,
    price: 19900,
    originalPrice: 24500,
    category: 'Domestic',
    theme: 'Religious',
    themeName: 'Religious',
    coverImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1200&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1200&auto=format&fit=crop'],
    overview: 'Experience Jaipur Pink City, Amer Fort elephant ride, Jodhpur Mehrangarh fort and Jaisalmer desert camel safari.',
    highlights: ['Jaisalmer Desert Night Camp & Folk Dance', 'Amer Fort Elephant Ride', 'Udaipur Lake Pichola Boat Ride'],
    itinerary: [
      { day: 1, title: 'Jaipur Pink City Welcome', description: 'Arrival in Jaipur, check-in to heritage hotel, visit Hawa Mahal.' },
      { day: 2, title: 'Amer Fort & City Palace', description: 'Amer Fort, Jal Mahal, Jantar Mantar and local handicraft bazaar.' },
      { day: 3, title: 'Jodhpur Blue City', description: 'Drive to Jodhpur, visit Mehrangarh Fort and Jaswant Thada.' },
      { day: 4, title: 'Jaisalmer Sand Dunes', description: 'Drive to Thar desert, camel safari, Kalbeliya folk dance & night camp stay.' },
      { day: 5, title: 'Jaisalmer Fort & Haveli', description: 'Explore Golden Fort, Patwon Ki Haveli and Gadisar Lake.' },
      { day: 6, title: 'Departure', description: 'Breakfast & drop at Jodhpur/Jaipur Airport.' },
    ],
    inclusions: ['Heritage Haveli & Desert Camp Stay', 'Daily Breakfast & Dinner', 'Desert Camel Safari & Folk Show', 'Private AC Vehicle'],
    exclusions: ['Monument Entrance Fees', 'Flight Airfare'],
    pricingTiers: [
      { category: 'Standard', price: 19900, hotel: '3 Star Heritage Haveli & Swiss Tent', meal: 'Breakfast & Dinner', transport: 'Private Sedan' },
      { category: 'Deluxe', price: 26900, hotel: '4 Star Palace Hotel & Luxury Tent', meal: 'Breakfast & Dinner', transport: 'Private Etios' },
      { category: 'Luxury', price: 42000, hotel: '5 Star Taj Lake Palace / Umaid Bhawan', meal: 'All Meals Included', transport: 'Private SUV' },
    ],
    isFeatured: true,
    rating: 4.95,
  },
  {
    _id: '7',
    id: '7',
    packageCode: 'PKG-KAS-001',
    title: 'Magical Kashmir Valley & Gulmarg Gondola Experience',
    slug: 'magical-kashmir-gulmarg-gondola-5-days',
    destination: 'Kashmir',
    duration: '5 Days / 4 Nights',
    startingPrice: 18500,
    price: 18500,
    originalPrice: 22000,
    category: 'Domestic',
    theme: 'Honeymoon Tour',
    themeName: 'Honeymoon Tour',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop'],
    overview: 'Dal Lake shikara ride, overnight luxury houseboat stay, Gulmarg cable car & Pahalgam valley tour.',
    highlights: ['Dal Lake Shikara Ride', 'Gulmarg Cable Car Gondola Ride', 'Luxury Houseboat Night Stay'],
    itinerary: [
      { day: 1, title: 'Srinagar Arrival & Shikara Ride', description: 'Airport transfer, check-in to luxury houseboat, evening Shikara ride on Dal Lake.' },
      { day: 2, title: 'Srinagar Mughal Gardens', description: 'Shalimar Bagh, Nishat Bagh, Cheshma Shahi and Shankaracharya Temple.' },
      { day: 3, title: 'Gulmarg Snow Excursion', description: 'Drive to Gulmarg, Gondola cable car ride to Apharwat peak snow point.' },
      { day: 4, title: 'Pahalgam Valley of Shepherds', description: 'Excursion to Pahalgam, Betaab Valley and Aru Valley pony ride.' },
      { day: 5, title: 'Departure', description: 'Breakfast & Srinagar Airport drop.' },
    ],
    inclusions: ['Houseboat & Hotel Stays', 'Daily Breakfast & Dinner', 'Shikara Ride Ticket', 'Private AC Vehicle'],
    exclusions: ['Gondola Phase 2 Tickets', 'Pony Ride Charges'],
    pricingTiers: [
      { category: 'Standard', price: 18500, hotel: 'Deluxe Houseboat & 3 Star Hotel', meal: 'Breakfast & Dinner', transport: 'Private Sedan' },
      { category: 'Deluxe', price: 23900, hotel: 'Luxury Houseboat & 4 Star Resort', meal: 'Breakfast & Dinner', transport: 'Private Etios' },
      { category: 'Luxury', price: 39500, hotel: 'Khyber Himalayan Resort & Spa', meal: 'All Meals Included', transport: 'Private Innova Crysta' },
    ],
    isFeatured: true,
    rating: 4.97,
  },
  {
    _id: '8',
    id: '8',
    packageCode: 'PKG-SIN-001',
    title: 'Singapore City & Sentosa Universal Studios Extravaganza',
    slug: 'singapore-city-sentosa-universal-studios-extravaganza',
    destination: 'Singapore & Sentosa Island',
    duration: '5 Days / 4 Nights',
    startingPrice: 48500,
    price: 48500,
    originalPrice: 55000,
    category: 'International',
    theme: 'Leisure',
    themeName: 'Leisure',
    coverImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1200&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1200&auto=format&fit=crop'],
    overview: 'Universal Studios Singapore 1-day pass, Gardens by the Bay Supertree Light Show, Marina Bay Sands & Night Safari.',
    highlights: ['Universal Studios 1-Day Pass', 'Gardens by the Bay Supertree Dome', 'Night Safari Tram Ride'],
    itinerary: [
      { day: 1, title: 'Arrival & Night Safari', description: 'Changi Airport transfer, hotel check-in and evening Night Safari tram tour.' },
      { day: 2, title: 'Singapore City Tour & Marina Bay', description: 'Merlion Park, Chinatown, Little India and Marina Bay SkyPark Observation Deck.' },
      { day: 3, title: 'Full Day Universal Studios', description: 'Transformers 3D ride, Mummy coaster, Jurassic Park & Hollywood zone.' },
      { day: 4, title: 'Sentosa Island Cable Car & Wings of Time', description: 'Sentosa cable car ride, S.E.A. Aquarium & Wings of Time laser show.' },
      { day: 5, title: 'Jewel Changi & Departure', description: 'Explore Jewel Changi rain vortex waterfall & flight departure.' },
    ],
    inclusions: ['4-Star Singapore City Hotel', 'Daily Buffet Breakfast', 'Universal Studios Pass', 'Airport Transfers'],
    exclusions: ['Singapore Visa Charges', 'Flight Tickets'],
    pricingTiers: [
      { category: 'Standard', price: 48500, hotel: '3 Star City Hotel', meal: 'Daily Breakfast', transport: 'Shared Coach' },
      { category: 'Deluxe', price: 62000, hotel: '4 Star Hotel in Orchard Road', meal: 'Breakfast & Dinner', transport: 'Private Cab' },
      { category: 'Luxury', price: 95000, hotel: 'Marina Bay Sands / Shangri-La', meal: 'All Meals Included', transport: 'Private Luxury Vehicle' },
    ],
    isFeatured: true,
    rating: 4.91,
  },
  {
    _id: '9',
    id: '9',
    packageCode: 'PKG-BAL-001',
    title: 'Exotic Bali Beach Resort & Ubud Culture Escapade',
    slug: 'exotic-bali-beach-ubud-culture-tour-6-days',
    destination: 'Bali',
    duration: '6 Days / 5 Nights',
    startingPrice: 39500,
    price: 39500,
    originalPrice: 45000,
    category: 'International',
    theme: 'Honeymoon Tour',
    themeName: 'Honeymoon Tour',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop',
    images: ['https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop'],
    overview: 'Private pool villa stay, Bali jungle swing photoshoot, Kintamani volcano view & Tanah Lot sunset temple.',
    highlights: ['Private Pool Villa in Seminyak', 'Bali Swing & Rice Terrace Photoshoot', 'Tanah Lot Sunset Temple'],
    itinerary: [
      { day: 1, title: 'Denpasar Welcome & Villa Check-in', description: 'Airport transfer, check-in to private pool villa in Seminyak.' },
      { day: 2, title: 'Ubud Swing & Tegenungan Waterfall', description: 'Famous Bali jungle swing, Tegallalang rice terraces & Tegenungan waterfall.' },
      { day: 3, title: 'Kintamani Volcano & Coffee Plantation', description: 'Mount Batur volcano view, Luwak coffee tasting & Tirta Empul holy spring.' },
      { day: 4, title: 'Nusa Penida Island Tour', description: 'Fast boat to Nusa Penida, Kelingking T-Rex beach & Broken Beach.' },
      { day: 5, title: 'Water Sports & Tanah Lot Temple', description: 'Parasailing combo at Benoa beach & sunset at Tanah Lot temple.' },
      { day: 6, title: 'Departure', description: 'Balinese spa massage, souvenir shopping & airport transfer.' },
    ],
    inclusions: ['Private Pool Villa & Resort Stay', 'Daily Breakfast', 'Nusa Penida Fast Boat Tickets', 'Private Driver & AC Car'],
    exclusions: ['Indonesia Visa on Arrival ($35)', 'Flight Airfare'],
    pricingTiers: [
      { category: 'Standard', price: 39500, hotel: '4 Star Kuta Resort', meal: 'Daily Breakfast', transport: 'Private AC Car' },
      { category: 'Deluxe', price: 49900, hotel: 'Private Pool Villa in Seminyak', meal: 'Breakfast & Candlelight Dinner', transport: 'Private Driver' },
      { category: 'Luxury', price: 79000, hotel: '5 Star Ayana / Mulia Resort Bali', meal: 'All Meals Included', transport: 'Private Luxury Van' },
    ],
    isFeatured: true,
    rating: 4.93,
  },
];

export const FALLBACK_DESTINATIONS = [
  {
    _id: '1',
    id: '1',
    name: 'TELAGANA',
    slug: 'telagana',
    state: 'Telangana',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop',
    description: 'Rich heritage, historic monuments like Charminar & Golconda, vibrant culture and serene lakefronts.',
    bestTimeToVisit: ['Nov - Feb'],
    isPopular: true,
  },
  {
    _id: '2',
    id: '2',
    name: 'Kerala',
    slug: 'kerala',
    state: 'Kerala',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    description: 'God\'s Own Country famous for serene backwaters, tea gardens & luxury houseboats.',
    bestTimeToVisit: ['Sep - Mar'],
    isPopular: true,
  },
  {
    _id: '3',
    id: '3',
    name: 'Maldives Overwater Bungalows',
    slug: 'maldives',
    state: 'Male Atoll',
    country: 'Maldives',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    description: 'World-renowned tropical paradise with overwater villas and crystal clear turquoise lagoons.',
    bestTimeToVisit: ['Nov - Apr'],
    isPopular: true,
  },
  {
    _id: '4',
    id: '4',
    name: 'Himachal & Manali',
    slug: 'himachal',
    state: 'Himachal Pradesh',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    description: 'High-altitude Himalayan resort town known for snow peaks, Solang Valley & Rohtang Pass.',
    bestTimeToVisit: ['Oct - Jun'],
    isPopular: true,
  },
  {
    _id: '5',
    id: '5',
    name: 'Goa Beaches & Nightlife',
    slug: 'goa',
    state: 'Goa',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
    description: 'Golden sand beaches, water sports, sunset cruises & vibrant nightlife.',
    bestTimeToVisit: ['Nov - Feb'],
    isPopular: true,
  },
  {
    _id: '6',
    id: '6',
    name: 'Rajasthan Royal Forts',
    slug: 'rajasthan',
    state: 'Rajasthan',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1200&auto=format&fit=crop',
    description: 'Royal palaces, Amer Fort elephant rides, desert sand dunes & cultural folk dances.',
    bestTimeToVisit: ['Oct - Mar'],
    isPopular: true,
  },
  {
    _id: '7',
    id: '7',
    name: 'Singapore & Sentosa Island',
    slug: 'singapore',
    state: 'Marina Bay',
    country: 'Singapore',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1200&auto=format&fit=crop',
    description: 'Gardens by the Bay, Universal Studios Singapore, Merlion Park & luxury shopping.',
    bestTimeToVisit: ['Year Round'],
    isPopular: true,
  },
  {
    _id: '8',
    id: '8',
    name: 'Bali Island Paradise',
    slug: 'bali',
    state: 'Bali Province',
    country: 'Indonesia',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop',
    description: 'Tropical island paradise known for private pool villas, Bali swing & Nusa Penida.',
    bestTimeToVisit: ['Apr - Oct'],
    isPopular: true,
  },
  {
    _id: '9',
    id: '9',
    name: 'Dubai Futuristic Oasis',
    slug: 'dubai',
    state: 'Dubai Emirate',
    country: 'United Arab Emirates',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1200&auto=format&fit=crop',
    description: 'Burj Khalifa skyline, luxury desert safari, Miracle Garden & theme parks.',
    bestTimeToVisit: ['Nov - Mar'],
    isPopular: true,
  },
  {
    _id: '10',
    id: '10',
    name: 'Vietnam & Ha Long Bay',
    slug: 'vietnam',
    state: 'Da Nang & Hanoi',
    country: 'Vietnam',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=1200&auto=format&fit=crop',
    description: 'Emerald bay cruises, Golden Hand bridge in Ba Na Hills & lantern city Hoi An.',
    bestTimeToVisit: ['Sep - Apr'],
    isPopular: true,
  },
  {
    _id: '11',
    id: '11',
    name: 'Kashmir Valley & Gulmarg',
    slug: 'kashmir',
    state: 'Jammu & Kashmir',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop',
    description: 'Paradise on earth with Dal Lake shikara rides, luxury houseboats & snow-capped peaks.',
    bestTimeToVisit: ['Mar - Oct'],
    isPopular: true,
  },
  {
    _id: '12',
    id: '12',
    name: 'Delhi Heritage & Capital',
    slug: 'delhi',
    state: 'Delhi NCR',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=1200&auto=format&fit=crop',
    description: 'Historic monuments, Qutub Minar, Red Fort, India Gate & street food capitals.',
    bestTimeToVisit: ['Oct - Mar'],
    isPopular: true,
  },
  {
    _id: '13',
    id: '13',
    name: 'Leh Ladakh High Passes',
    slug: 'ladakh',
    state: 'Ladakh',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    description: 'Pangong Lake azure waters, Khardung La motorcycling & ancient Buddhist monasteries.',
    bestTimeToVisit: ['May - Sep'],
    isPopular: true,
  },
  {
    _id: '14',
    id: '14',
    name: 'Agra Taj Mahal Wonders',
    slug: 'agra',
    state: 'Uttar Pradesh',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1200&auto=format&fit=crop',
    description: 'Home of the white marble Taj Mahal, Agra Fort & Mughal architectural masterpieces.',
    bestTimeToVisit: ['Oct - Mar'],
    isPopular: true,
  },
  {
    _id: '15',
    id: '15',
    name: 'Varanasi Sacred Ganges',
    slug: 'varanasi',
    state: 'Uttar Pradesh',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=1200&auto=format&fit=crop',
    description: 'Spiritual heart of India, ancient Ganga Aarti ceremonies, boat rides & Kashi temples.',
    bestTimeToVisit: ['Nov - Feb'],
    isPopular: true,
  },
  {
    _id: '16',
    id: '16',
    name: 'Darjeeling Tea & Himalayas',
    slug: 'darjeeling',
    state: 'West Bengal',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1200&auto=format&fit=crop',
    description: 'Queen of the Hills, Himalayan Toy Train heritage, Kanchenjunga views & tea gardens.',
    bestTimeToVisit: ['Apr - Jun, Oct - Dec'],
    isPopular: true,
  },
  {
    _id: '17',
    id: '17',
    name: 'Andaman & Radhanagar Beach',
    slug: 'andaman',
    state: 'Andaman & Nicobar',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?q=80&w=1200&auto=format&fit=crop',
    description: 'Pristine island white sands, scuba diving coral reefs, Havelock & Cellular Jail.',
    bestTimeToVisit: ['Oct - May'],
    isPopular: true,
  },
  {
    _id: '18',
    id: '18',
    name: 'Ooty & Kodaikanal Hills',
    slug: 'ooty',
    state: 'Tamil Nadu',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop',
    description: 'Nilgiri mountain railway, botanical gardens, misty lakes & eucalyptus plantations.',
    bestTimeToVisit: ['Oct - Jun'],
    isPopular: true,
  },
  {
    _id: '19',
    id: '19',
    name: 'Coorg Coffee Country',
    slug: 'coorg',
    state: 'Karnataka',
    country: 'India',
    category: 'Domestic',
    isDomestic: true,
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    description: 'Scotland of India, aromatic coffee plantations, Abbey Falls & Dubare Elephant Camp.',
    bestTimeToVisit: ['Oct - Apr'],
    isPopular: true,
  },
  {
    _id: '20',
    id: '20',
    name: 'Thailand Bangkok & Phuket',
    slug: 'thailand',
    state: 'Bangkok & Phuket',
    country: 'Thailand',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?q=80&w=1200&auto=format&fit=crop',
    description: 'Phi Phi island speedboat tours, Grand Palace temple, floating markets & nightlife.',
    bestTimeToVisit: ['Nov - Apr'],
    isPopular: true,
  },
  {
    _id: '21',
    id: '21',
    name: 'Malaysia & Genting Highlands',
    slug: 'malaysia',
    state: 'Kuala Lumpur',
    country: 'Malaysia',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=1200&auto=format&fit=crop',
    description: 'Petronas Twin Towers, Batu Caves, Genting cable car & Langkawi archipelago.',
    bestTimeToVisit: ['Year Round'],
    isPopular: true,
  },
  {
    _id: '22',
    id: '22',
    name: 'Switzerland Alpine Dreams',
    slug: 'switzerland',
    state: 'Interlaken & Zurich',
    country: 'Switzerland',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1200&auto=format&fit=crop',
    description: 'Jungfraujoch Top of Europe, Mount Titlis revolving cable car, Lucerne lake & snow peaks.',
    bestTimeToVisit: ['May - Oct, Dec - Mar'],
    isPopular: true,
  },
  {
    _id: '23',
    id: '23',
    name: 'Europe Grand Tour & Paris',
    slug: 'europe',
    state: 'Paris, Rome & Amsterdam',
    country: 'France / Italy',
    category: 'International',
    isDomestic: false,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200&auto=format&fit=crop',
    description: 'Eiffel Tower illuminations, Louvre Museum, Rome Colosseum & Venice gondola rides.',
    bestTimeToVisit: ['Apr - Oct'],
    isPopular: true,
  },
];

export const FALLBACK_THEMES = [
  {
    _id: 't1',
    id: 't1',
    name: 'Honeymoon Tour',
    slug: 'honeymoon-tour',
    rating: '4.9 ★ (348 Reviews)',
    imageUrl: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=1200&auto=format&fit=crop',
    description: 'Romantic getaways with candlelight dinners, luxury stays, scenic sunset moments, and memorable couple experiences.',
  },
  {
    _id: 't2',
    id: 't2',
    name: 'Leisure',
    slug: 'leisure',
    rating: '4.8 ★ (162 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
    description: 'Easygoing holidays that blend beach relaxation, resort stays, and curated city or coastal sightseeing.',
  },
  {
    _id: 't3',
    id: 't3',
    name: 'Hill Station',
    slug: 'hill-station',
    rating: '4.9 ★ (81 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop',
    description: 'Cool-weather escapes with mountain views, pine valleys, tea gardens, and peaceful nature retreats.',
  },
  {
    _id: 't4',
    id: 't4',
    name: 'Trekking',
    slug: 'trekking',
    rating: '5.0 ★ (55 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop',
    description: 'Trail-based adventures through scenic mountains, guided treks, camp stays, and landscape-rich routes.',
  },
  {
    _id: 't5',
    id: 't5',
    name: 'Adventure',
    slug: 'adventure',
    rating: '4.9 ★ (141 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?q=80&w=1200&auto=format&fit=crop',
    description: 'High-energy trips featuring rafting, zipline rides, off-road thrills, and adrenaline-filled experiences.',
  },
  {
    _id: 't6',
    id: 't6',
    name: 'Religious',
    slug: 'religious',
    rating: '5.0 ★ (41 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=1200&auto=format&fit=crop',
    description: 'Sacred journeys to temples, heritage sites, and peaceful spiritual destinations with guided comfort.',
  },
  {
    _id: 't7',
    id: 't7',
    name: 'Family Tour',
    slug: 'family-tour',
    rating: '4.8 ★ (210 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=1200&auto=format&fit=crop',
    description: 'Comfort-focused family holidays with sightseeing, kid-friendly activities, and memorable shared experiences.',
  },
  {
    _id: 't8',
    id: 't8',
    name: 'Wildlife Safari',
    slug: 'wildlife-safari',
    rating: '4.9 ★ (35 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?q=80&w=1200&auto=format&fit=crop',
    description: 'Wildlife-rich escapes with jungle safaris, nature lodges, forest drives, and unforgettable animal encounters.',
  },
];

export const FALLBACK_ENQUIRIES = [
  {
    _id: 'enq_1',
    enquiryId: 'ENQ-2026-001',
    fullName: 'Ramesh Kumar',
    email: 'ramesh.kumar@gmail.com',
    mobile: '+91 98490 12345',
    destination: 'TELAGANA',
    package: 'Telangana & Hyderabad City of Pearls Heritage Tour',
    travelDate: '2026-08-25',
    adults: 2,
    children: 1,
    budget: 35000,
    status: 'New',
    priority: 'High',
    message: 'Interested in family package with Ramoji Film City pass and 4-star stay.',
    createdAt: '2026-08-18T09:00:00.000Z'
  },
  {
    _id: 'enq_2',
    enquiryId: 'ENQ-2026-002',
    fullName: 'Sunita Verma',
    email: 'sunita.v@outlook.com',
    mobile: '+91 97012 88452',
    destination: 'Kerala',
    package: 'Kerala Backwaters & Houseboat Paradise',
    travelDate: '2026-09-10',
    adults: 2,
    children: 0,
    budget: 48000,
    status: 'Contacted',
    priority: 'Urgent',
    message: 'Looking for honeymoon villa in Munnar with private pool and Alleppey luxury houseboat.',
    createdAt: '2026-08-17T14:30:00.000Z'
  },
  {
    _id: 'enq_3',
    enquiryId: 'ENQ-2026-003',
    fullName: 'Amit Patel',
    email: 'amit.patel@techcorp.in',
    mobile: '+91 99887 65432',
    destination: 'Maldives',
    package: 'Maldives Luxury Water Villa Honeymoon Escape',
    travelDate: '2026-10-05',
    adults: 2,
    children: 0,
    budget: 185000,
    status: 'Qualified',
    priority: 'High',
    message: 'Require all-inclusive resort with speed boat transfer and sunset dinner.',
    createdAt: '2026-08-16T11:15:00.000Z'
  },
  {
    _id: 'enq_4',
    enquiryId: 'ENQ-2026-004',
    fullName: 'Priya Sharma',
    email: 'priya.sharma@yahoo.com',
    mobile: '+91 98112 34567',
    destination: 'Himachal & Manali',
    package: 'Manali & Solang Snow Adventure',
    travelDate: '2026-11-20',
    adults: 4,
    children: 2,
    budget: 65000,
    status: 'Converted',
    priority: 'Medium',
    message: 'Family vacation requesting Rohtang Pass permit and local AC Volvo transport.',
    createdAt: '2026-08-15T16:45:00.000Z'
  },
  {
    _id: 'enq_5',
    enquiryId: 'ENQ-2026-005',
    fullName: 'Vikram Singh',
    email: 'vikram.singh@gmail.com',
    mobile: '+91 96543 21098',
    destination: 'Rajasthan',
    package: 'Royal Rajasthan Forts & Desert Safari',
    travelDate: '2026-11-15',
    adults: 3,
    children: 1,
    budget: 55000,
    status: 'New',
    priority: 'Medium',
    message: 'Interested in Jaisalmer desert camel safari and heritage palace stays.',
    createdAt: '2026-08-14T10:20:00.000Z'
  },
  {
    _id: 'enq_gen_1',
    enquiryId: 'ENQ-2026-006',
    fullName: 'Naveen Kumar',
    email: 'naveen@gmail.com',
    mobile: '+91 98765 43210',
    destination: 'Maldives',
    preferredDestination: 'Maldives',
    package: null,
    packageName: null,
    travelDate: '2026-11-10',
    adults: 2,
    children: 0,
    budget: null,
    status: 'New',
    priority: 'High',
    message: 'General custom trip enquiry submitted from Home Page for Maldives.',
    createdAt: '2026-08-19T10:00:00.000Z'
  },
  {
    _id: 'enq_6',
    enquiryId: 'ENQ-2026-006',
    fullName: 'Ananya Roy',
    email: 'ananya.roy@gmail.com',
    mobile: '+91 98300 44556',
    destination: 'Singapore & Sentosa Island',
    package: 'Singapore City & Sentosa Universal Studios Extravaganza',
    travelDate: '2026-12-01',
    adults: 2,
    children: 1,
    budget: 120000,
    status: 'Contacted',
    priority: 'High',
    message: 'Universal Studios express pass + Marina Bay Sands skypark entry needed.',
    createdAt: '2026-08-13T08:50:00.000Z'
  },
  {
    _id: 'enq_7',
    enquiryId: 'ENQ-2026-007',
    fullName: 'Rajesh Naidu',
    email: 'rajesh.naidu@gmail.com',
    mobile: '+91 94401 98765',
    destination: 'Bali Island Paradise',
    package: 'Bali Tropical Island & Private Pool Villa Escape',
    travelDate: '2026-09-25',
    adults: 2,
    children: 0,
    budget: 95000,
    status: 'Qualified',
    priority: 'Medium',
    message: 'Ubud jungle resort + Seminyak beach club pass.',
    createdAt: '2026-08-12T15:10:00.000Z'
  }
];
