/* ─────────────────────────────────────────────────────────────
   MOBILE APP FALLBACK DATASET
   Matches Flutter package_service.dart, destination_service.dart,
   and theme_service.dart exactly to ensure 100% data parity.
───────────────────────────────────────────────────────────── */

export const FALLBACK_PACKAGES = [
  {
    _id: '1',
    id: '1',
    packageCode: 'PKG-GOA-001',
    title: 'Vibrant Goa Beach & Water Sports Getaway',
    slug: 'vibrant-goa-beach-getaway-4-days',
    destination: 'Goa, India',
    duration: '4 Days / 3 Nights',
    startingPrice: 12900,
    price: 12900,
    originalPrice: 15900,
    category: 'Domestic',
    theme: 'Leisure',
    themeName: 'Leisure',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'Experience North and South Goa beach hopping, Mandovi river sunset cruise, and thrill water sports in Calangute.',
    highlights: ['4-Star Beach Resort Stay', 'Mandovi River Sunset Cruise', 'Parasailing & Jet Skiing Combo', 'Old Goa Churches'],
    itinerary: [
      { day: 1, title: 'Arrival & Beach Chill', description: 'Airport transfer, check-in to resort, and evening stroll at Baga beach.' },
      { day: 2, title: 'North Goa & Water Sports', description: 'Parasailing, jet skiing, banana ride, and Fort Aguada photoshoot.' },
      { day: 3, title: 'South Goa & Sunset Cruise', description: 'Visit Basilica of Bom Jesus, Mangueshi Temple, and Mandovi river cruise.' },
      { day: 4, title: 'Departure', description: 'Breakfast & souvenir shopping before airport drop.' },
    ],
    inclusions: ['4-Star Resort Stay', 'Daily Buffet Breakfast', 'Private AC Sedan Airport Transfer', 'Water Sports Combo'],
    exclusions: ['Flight Airfare', 'Personal Expenses'],
    pricingTiers: [
      { category: 'Standard', price: 12900, hotel: '3 Star Beachside Hotel', meal: 'Daily Breakfast', transport: 'Shared AC Coach' },
      { category: 'Deluxe', price: 15900, hotel: '4 Star Luxury Resort', meal: 'Breakfast & Dinner', transport: 'Private AC Sedan' },
      { category: 'Luxury', price: 24900, hotel: '5 Star Taj / Marriott Beach Resort', meal: 'All Meals Included', transport: 'Private SUV' },
    ],
    isFeatured: true,
    rating: 4.88,
  },
  {
    _id: '2',
    id: '2',
    packageCode: 'PKG-HIM-001',
    title: 'Scenic Manali & Solang Snow Adventure',
    slug: 'scenic-manali-solang-snow-adventure-5-days',
    destination: 'Himachal Pradesh, India',
    duration: '5 Days / 4 Nights',
    startingPrice: 16500,
    price: 16500,
    originalPrice: 19500,
    category: 'Domestic',
    theme: 'Hill Station',
    themeName: 'Hill Station',
    coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'Explore Hadimba Temple, Mall Road shopping, Solang Valley ATV rides & Rohtang snow point.',
    highlights: ['Solang Valley Snow Sports', 'Rohtang Pass Day Trip', 'Private Mountain View Resort'],
    itinerary: [
      { day: 1, title: 'Arrival in Manali', description: 'Check-in to mountain resort and rest.' },
      { day: 2, title: 'Local Sightseeing', description: 'Hadimba Temple, Vashisht Hot Springs, and Mall Road.' },
      { day: 3, title: 'Solang Valley Adventure', description: 'Paragliding, ropeway, and snow sports.' },
      { day: 4, title: 'Atal Tunnel & Sissu', description: 'Excursion to Lahaul valley via Atal Tunnel.' },
      { day: 5, title: 'Departure', description: 'Breakfast & Volvo bus drop.' },
    ],
    inclusions: ['Mountain View Resort Stay', 'Breakfast & Dinner', 'Private Cab Sightseeing'],
    exclusions: ['Heater Charges', 'Personal Shopping'],
    pricingTiers: [
      { category: 'Standard', price: 16500, hotel: '3 Star Mountain View Hotel', meal: 'Breakfast & Dinner', transport: 'Private Alto/Dzire' },
      { category: 'Deluxe', price: 21900, hotel: '4 Star Luxury Cottage Resort', meal: 'Breakfast & Dinner', transport: 'Private Etios/Sedan' },
      { category: 'Luxury', price: 32000, hotel: '5 Star Span Resort & Spa', meal: 'All Meals Included', transport: 'Private Innova Crysta' },
    ],
    isFeatured: true,
    rating: 4.92,
  },
  {
    _id: '3',
    id: '3',
    packageCode: 'PKG-MAL-001',
    title: 'Maldives Private Water Villa & Snorkeling Paradise',
    slug: 'maldives-water-villa-honeymoon-5-days',
    destination: 'Maldives',
    duration: '5 Days / 4 Nights',
    startingPrice: 59000,
    price: 59000,
    originalPrice: 68000,
    category: 'International',
    theme: 'Honeymoon Tour',
    themeName: 'Honeymoon Tour',
    coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: '5-star private island resort with glass floor water bungalow, speedboat transfer & all meals.',
    highlights: ['Overwater Bungalow with Ocean Access', 'Speedboat Airport Transfer', 'Sunset Dolphin Cruise'],
    itinerary: [
      { day: 1, title: 'Speedboat Welcome to Resort', description: 'Speedboat transfer to island resort & overwater bungalow check-in.' },
      { day: 2, title: 'Snorkeling & House Reef Exploration', description: 'Guided snorkeling session among coral reefs & sea turtles.' },
      { day: 3, title: 'Sunset Dolphin Cruise', description: 'Romantic boat cruise with champagne & dolphin sightings.' },
      { day: 4, title: 'Island Spa & Leisure', description: 'Relaxing couples massage and beachside dinner.' },
      { day: 5, title: 'Departure', description: 'Buffet breakfast & speedboat transfer to Male International Airport.' },
    ],
    inclusions: ['5-Star Overwater Bungalow Stay', 'All-Inclusive Full Board Meals', 'Roundtrip Speedboat Airport Transfer', 'Guided Snorkeling Equipment'],
    exclusions: ['International Flight Tickets', 'Spa Premium Treatments'],
    pricingTiers: [
      { category: 'Standard', price: 59000, hotel: 'Beach Villa with Lagoon Access', meal: 'Breakfast & Dinner', transport: 'Shared Speedboat' },
      { category: 'Deluxe', price: 79000, hotel: 'Overwater Bungalow with Sunset View', meal: 'Full Board (All Meals)', transport: 'Express Speedboat' },
      { category: 'Luxury', price: 115000, hotel: 'Private Pool Ocean Suite', meal: 'Ultra All-Inclusive Premium Drinks', transport: 'Private Seaplane Flight' },
    ],
    isFeatured: true,
    rating: 4.96,
  },
  {
    _id: '4',
    id: '4',
    packageCode: 'PKG-KER-001',
    title: 'Kerala Backwaters & Munnar Hills Luxury Tour',
    slug: 'kerala-backwaters-munnar-luxury-tour-6-days',
    destination: 'Kerala, India',
    duration: '6 Days / 5 Nights',
    startingPrice: 18900,
    price: 18900,
    originalPrice: 22500,
    category: 'Domestic',
    theme: 'Family Tour',
    themeName: 'Family Tour',
    coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    mainImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    ],
    overview: 'Explore tea gardens of Munnar, Periyar wildlife sanctuary, and overnight luxury houseboat cruise in Alleppey.',
    highlights: ['Overnight Private Houseboat Cruise', 'Munnar Tea Plantation Tour', 'Periyar Boat Safari'],
    itinerary: [
      { day: 1, title: 'Cochin to Munnar Drive', description: 'Scenic drive past Cheeyappara waterfalls to Munnar tea country.' },
      { day: 2, title: 'Munnar Tea Gardens & Eravikulam', description: 'Visit Tea Museum, Mattupetty Dam, and spot Nilgiri Tahr.' },
      { day: 3, title: 'Thekkady Wildlife Sanctuary', description: 'Drive to Thekkady, spice plantation visit, and evening Kathakali show.' },
      { day: 4, title: 'Alleppey Houseboat Cruise', description: 'Board luxury private houseboat, traditional Kerala lunch & canal cruise.' },
      { day: 5, title: 'Kovalam Beach Resort', description: 'Drive to Kovalam beach for relaxation and seafood.' },
      { day: 6, title: 'Trivandrum Departure', description: 'Visit Padmanabhaswamy temple & drop at Trivandrum Airport.' },
    ],
    inclusions: ['Munnar & Thekkady Resort Stays', 'Private Luxury Houseboat Cruise', 'Daily Breakfast & Houseboat All Meals', 'Private AC Sedan Car'],
    exclusions: ['Train / Flight Ticket', 'Kathakali Entry Tickets'],
    pricingTiers: [
      { category: 'Standard', price: 18900, hotel: '3 Star Resort & Deluxe Houseboat', meal: 'Daily Breakfast', transport: 'Private Sedan' },
      { category: 'Deluxe', price: 24500, hotel: '4 Star Tea Garden Resort & Luxury Houseboat', meal: 'Breakfast & Dinner', transport: 'Private Etios' },
      { category: 'Luxury', price: 38900, hotel: '5 Star Taj Kumarakom / Spice Village', meal: 'All Meals Included', transport: 'Private Innova Crysta' },
    ],
    isFeatured: true,
    rating: 4.91,
  },
];

export const FALLBACK_DESTINATIONS = [
  {
    _id: '1',
    id: '1',
    name: 'TELAGANA',
    slug: 'telagana',
    state: 'Telangana',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop',
    description: 'Rich heritage, historic monuments like Charminar & Golconda, vibrant culture and serene lakefronts.',
    bestTimeToVisit: ['Nov - Feb'],
    isPopular: true,
  },
  {
    _id: '2',
    id: '2',
    name: 'Kerala',
    slug: 'kerala',
    state: 'Kerala',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=1200&auto=format&fit=crop',
    description: 'God\'s Own Country famous for serene backwaters, tea gardens & luxury houseboats.',
    bestTimeToVisit: ['Sep - Mar'],
    isPopular: true,
  },
  {
    _id: '3',
    id: '3',
    name: 'Maldives',
    slug: 'maldives',
    state: 'Male Atoll',
    country: 'Maldives',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1200&auto=format&fit=crop',
    description: 'World-renowned tropical paradise with overwater villas and crystal clear turquoise lagoons.',
    bestTimeToVisit: ['Nov - Apr'],
    isPopular: true,
  },
  {
    _id: '4',
    id: '4',
    name: 'Himachal & Manali',
    slug: 'himachal',
    state: 'Himachal Pradesh',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=1200&auto=format&fit=crop',
    description: 'High-altitude Himalayan resort town known for snow peaks, Solang Valley & Rohtang Pass.',
    bestTimeToVisit: ['Oct - Jun'],
    isPopular: true,
  },
  {
    _id: '5',
    id: '5',
    name: 'Goa',
    slug: 'goa',
    state: 'Goa',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop',
    description: 'Golden sand beaches, water sports, sunset cruises & vibrant nightlife.',
    bestTimeToVisit: ['Nov - Feb'],
    isPopular: true,
  },
  {
    _id: '6',
    id: '6',
    name: 'Rajasthan',
    slug: 'rajasthan',
    state: 'Rajasthan',
    country: 'India',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1200&auto=format&fit=crop',
    description: 'Royal palaces, Amer Fort elephant rides, desert sand dunes & cultural folk dances.',
    bestTimeToVisit: ['Oct - Mar'],
    isPopular: true,
  },
];

export const FALLBACK_THEMES = [
  {
    _id: 't1',
    id: 't1',
    name: 'Honeymoon Tour',
    slug: 'honeymoon-tour',
    rating: '4.9 ★ (348 Reviews)',
    imageUrl: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=1200&auto=format&fit=crop',
    description: 'Romantic getaways with candlelight dinners, luxury stays, scenic sunset moments, and memorable couple experiences.',
  },
  {
    _id: 't2',
    id: 't2',
    name: 'Leisure',
    slug: 'leisure',
    rating: '4.8 ★ (162 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
    description: 'Easygoing holidays that blend beach relaxation, resort stays, and curated city or coastal sightseeing.',
  },
  {
    _id: 't3',
    id: 't3',
    name: 'Hill Station',
    slug: 'hill-station',
    rating: '4.9 ★ (81 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop',
    description: 'Cool-weather escapes with mountain views, pine valleys, tea gardens, and peaceful nature retreats.',
  },
  {
    _id: 't4',
    id: 't4',
    name: 'Trekking',
    slug: 'trekking',
    rating: '5.0 ★ (55 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop',
    description: 'Trail-based adventures through scenic mountains, guided treks, camp stays, and landscape-rich routes.',
  },
  {
    _id: 't5',
    id: 't5',
    name: 'Adventure',
    slug: 'adventure',
    rating: '4.9 ★ (141 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?q=80&w=1200&auto=format&fit=crop',
    description: 'High-energy trips featuring rafting, zipline rides, off-road thrills, and adrenaline-filled experiences.',
  },
  {
    _id: 't6',
    id: 't6',
    name: 'Religious',
    slug: 'religious',
    rating: '5.0 ★ (41 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=1200&auto=format&fit=crop',
    description: 'Sacred journeys to temples, heritage sites, and peaceful spiritual destinations with guided comfort.',
  },
  {
    _id: 't7',
    id: 't7',
    name: 'Family Tour',
    slug: 'family-tour',
    rating: '4.8 ★ (210 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=1200&auto=format&fit=crop',
    description: 'Comfort-focused family holidays with sightseeing, kid-friendly activities, and memorable shared experiences.',
  },
  {
    _id: 't8',
    id: 't8',
    name: 'Wildlife Safari',
    slug: 'wildlife-safari',
    rating: '4.9 ★ (35 Packages)',
    imageUrl: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?q=80&w=1200&auto=format&fit=crop',
    description: 'Wildlife-rich escapes with jungle safaris, nature lodges, forest drives, and unforgettable animal encounters.',
  },
];
